os:
  - linux

git:
  depth: 1
  submodules: false

language: cpp

compiler:
- clang

#env:
#- BUILDTYPE=Release TARGET=tutorial

before_install:
- sudo apt-get -qq update
# Only ITK 3 is available in Ubuntu 12.04
# v4 is required -> install from git
- git clone git://itk.org/ITK.git /tmp/ITK
- mkdir -p /tmp/ITK/build
- cd /tmp/ITK/build
- cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
- make -j 4 
- sudo make install

install:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build && cd build && cmake ..

script:
- make -j 4

branches:
  only:
  - develop
  - master
  - feature/explicit
  - merging-with-explicit
cache:
- apt
notifications:
  email:
    recipients:
    - angiotk-commits@cemosis.fr
    on_success: change
    on_failure: change
